package br.com.ifce.mflj.estacao.sensor.acidez;

/**
* br/com/ifce/mflj/estacao/sensor/acidez/ISensorAcidezHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SensorDeAcidez.idl
* Quarta-feira, 8 de Abril de 2015 08h45min25s BRT
*/

public final class ISensorAcidezHolder implements org.omg.CORBA.portable.Streamable
{
  public br.com.ifce.mflj.estacao.sensor.acidez.ISensorAcidez value = null;

  public ISensorAcidezHolder ()
  {
  }

  public ISensorAcidezHolder (br.com.ifce.mflj.estacao.sensor.acidez.ISensorAcidez initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = br.com.ifce.mflj.estacao.sensor.acidez.ISensorAcidezHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    br.com.ifce.mflj.estacao.sensor.acidez.ISensorAcidezHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return br.com.ifce.mflj.estacao.sensor.acidez.ISensorAcidezHelper.type ();
  }

}
