package br.edu.ifce.mflj.museu.guarda;


/**
* br/edu/ifce/mflj/museu/guarda/_IGuardaStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Guarda.idl
* Monday, May 2, 2016 8:18:58 AM BRT
*/

public class _IGuardaStub extends org.omg.CORBA.portable.ObjectImpl implements br.edu.ifce.mflj.museu.guarda.IGuarda
{

  public void entradaDeCliente ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("entradaDeCliente", true);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                entradaDeCliente (        );
            } finally {
                _releaseReply ($in);
            }
  } // entradaDeCliente

  public void saidaDeCliente ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("saidaDeCliente", true);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                saidaDeCliente (        );
            } finally {
                _releaseReply ($in);
            }
  } // saidaDeCliente

  public void entradaNaoAutorizada ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("entradaNaoAutorizada", true);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                entradaNaoAutorizada (        );
            } finally {
                _releaseReply ($in);
            }
  } // entradaNaoAutorizada

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:br/edu/ifce/mflj/museu/guarda/IGuarda:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _IGuardaStub
