package br.edu.ifce.mflj.museu.guarda;


/**
* br/edu/ifce/mflj/museu/guarda/IGuardaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Guarda.idl
* Monday, May 2, 2016 8:18:58 AM BRT
*/

public abstract class IGuardaPOA extends org.omg.PortableServer.Servant
 implements br.edu.ifce.mflj.museu.guarda.IGuardaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("entradaDeCliente", new java.lang.Integer (0));
    _methods.put ("saidaDeCliente", new java.lang.Integer (1));
    _methods.put ("entradaNaoAutorizada", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // br/edu/ifce/mflj/museu/guarda/IGuarda/entradaDeCliente
       {
         this.entradaDeCliente ();
         out = $rh.createReply();
         break;
       }

       case 1:  // br/edu/ifce/mflj/museu/guarda/IGuarda/saidaDeCliente
       {
         this.saidaDeCliente ();
         out = $rh.createReply();
         break;
       }

       case 2:  // br/edu/ifce/mflj/museu/guarda/IGuarda/entradaNaoAutorizada
       {
         this.entradaNaoAutorizada ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:br/edu/ifce/mflj/museu/guarda/IGuarda:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public IGuarda _this() 
  {
    return IGuardaHelper.narrow(
    super._this_object());
  }

  public IGuarda _this(org.omg.CORBA.ORB orb) 
  {
    return IGuardaHelper.narrow(
    super._this_object(orb));
  }


} // class IGuardaPOA
