package br.edu.ifce.mflj.museu.guarda;


/**
* br/edu/ifce/mflj/museu/guarda/IGuarda.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Guarda.idl
* Monday, May 2, 2016 8:18:58 AM BRT
*/

public interface IGuarda extends IGuardaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IGuarda
