package br.edu.ifce.mflj.museu.guarda;

/**
* br/edu/ifce/mflj/museu/guarda/IGuardaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Guarda.idl
* Monday, May 2, 2016 8:18:58 AM BRT
*/

public final class IGuardaHolder implements org.omg.CORBA.portable.Streamable
{
  public br.edu.ifce.mflj.museu.guarda.IGuarda value = null;

  public IGuardaHolder ()
  {
  }

  public IGuardaHolder (br.edu.ifce.mflj.museu.guarda.IGuarda initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = br.edu.ifce.mflj.museu.guarda.IGuardaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    br.edu.ifce.mflj.museu.guarda.IGuardaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return br.edu.ifce.mflj.museu.guarda.IGuardaHelper.type ();
  }

}
