package br.edu.ifce.mflj.museu.guarda;


/**
* br/edu/ifce/mflj/museu/guarda/IGuardaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Guarda.idl
* Monday, May 2, 2016 8:18:58 AM BRT
*/

public interface IGuardaOperations 
{
  void entradaDeCliente ();
  void saidaDeCliente ();
  void entradaNaoAutorizada ();
} // interface IGuardaOperations
