package br.edu.ifce.mflj.museu.guarda;


/**
* br/edu/ifce/mflj/museu/guarda/IGuardaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Guarda.idl
* Monday, May 2, 2016 8:18:58 AM BRT
*/

abstract public class IGuardaHelper
{
  private static String  _id = "IDL:br/edu/ifce/mflj/museu/guarda/IGuarda:1.0";

  public static void insert (org.omg.CORBA.Any a, br.edu.ifce.mflj.museu.guarda.IGuarda that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static br.edu.ifce.mflj.museu.guarda.IGuarda extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (br.edu.ifce.mflj.museu.guarda.IGuardaHelper.id (), "IGuarda");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static br.edu.ifce.mflj.museu.guarda.IGuarda read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_IGuardaStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, br.edu.ifce.mflj.museu.guarda.IGuarda value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static br.edu.ifce.mflj.museu.guarda.IGuarda narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof br.edu.ifce.mflj.museu.guarda.IGuarda)
      return (br.edu.ifce.mflj.museu.guarda.IGuarda)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      br.edu.ifce.mflj.museu.guarda._IGuardaStub stub = new br.edu.ifce.mflj.museu.guarda._IGuardaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static br.edu.ifce.mflj.museu.guarda.IGuarda unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof br.edu.ifce.mflj.museu.guarda.IGuarda)
      return (br.edu.ifce.mflj.museu.guarda.IGuarda)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      br.edu.ifce.mflj.museu.guarda._IGuardaStub stub = new br.edu.ifce.mflj.museu.guarda._IGuardaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
