module br {
    module com {
	module ifce {
	    module mflj {
		module estacao {
		    module sensor {
			module acidez {
			    interface ISensorAcidez {
				boolean ligado();
				wstring obterLeitura();
				wstring obterIdentificador();
				void configurarLeitura( in wstring leitura );
			    };
            	    	};
		    };
		};
	    };
	};
    };
};
